//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonilaAccountingSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerInfo
    {
        public int id { get; set; }
        public string customerName { get; set; }
        public string customerPhoneNumber { get; set; }
        public string customer_mobile { get; set; }
        public string customerAddress { get; set; }
        public string customerDisc { get; set; }
        public string customerBirthDate { get; set; }
        public string customerNationalCode { get; set; }
        public string userName { get; set; }
        public string timeStamp { get; set; }
        public Nullable<int> ReagentCode { get; set; }
    }
}
