//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonilaAccountingSoftware.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RonilaDBEntities : DbContext
    {
        public RonilaDBEntities()
            : base("name=RonilaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UnitInfo> UnitInfoes { get; set; }
        public virtual DbSet<DefineStore> DefineStores { get; set; }
        public virtual DbSet<CustomerInfo> CustomerInfoes { get; set; }
        public virtual DbSet<DefineGoodsGroup> DefineGoodsGroups { get; set; }
        public virtual DbSet<DefineGood> DefineGoods { get; set; }
        public virtual DbSet<StoreInput> StoreInputs { get; set; }
        public virtual DbSet<SupplierInfo> SupplierInfoes { get; set; }
        public virtual DbSet<DefineBankAccount> DefineBankAccounts { get; set; }
        public virtual DbSet<DefineChakInfo> DefineChakInfoes { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<StoreInfo> StoreInfoes { get; set; }
    }
}
