//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonilaAccountingSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefineGood
    {
        public int id { get; set; }
        public string goodsCode { get; set; }
        public string goodsName { get; set; }
        public Nullable<int> goodsGroup { get; set; }
        public Nullable<int> goodsStore { get; set; }
        public Nullable<int> goodsUnit { get; set; }
        public string goodsDisc { get; set; }
        public Nullable<double> goodsMin { get; set; }
        public Nullable<double> goodsMax { get; set; }
        public Nullable<double> goosOrderPoint { get; set; }
        public Nullable<double> goodsWeight { get; set; }
        public byte[] goodsPic { get; set; }
        public string userName { get; set; }
        public string timeStamp { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
