//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonilaAccountingSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefineStore
    {
        public int id { get; set; }
        public string storeName { get; set; }
        public string storeDisc { get; set; }
        public string userName { get; set; }
        public string timeStamp { get; set; }
    }
}
