//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonilaAccountingSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefineBankAccount
    {
        public int id { get; set; }
        public string bankName { get; set; }
        public string bankCartNumber { get; set; }
        public string bankAccountNumber { get; set; }
        public string bankShabaNumber { get; set; }
        public string bandDisc { get; set; }
        public string userName { get; set; }
        public string timeStamp { get; set; }
    }
}
