//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonilaAccountingSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefineChakInfo
    {
        public int id { get; set; }
        public Nullable<int> storeInputSupplierCode { get; set; }
        public string storeInputFactorNumber { get; set; }
        public string chakNumSayadi { get; set; }
        public string chakSerial { get; set; }
        public Nullable<double> chakPrice { get; set; }
        public string chakDateSodor { get; set; }
        public string chakPasDay { get; set; }
        public Nullable<int> chakaccountNumberCode { get; set; }
        public string chakBranch { get; set; }
        public string chakInFace { get; set; }
        public Nullable<int> chakAlarmDay { get; set; }
        public string chakAlarmDate { get; set; }
        public string chakDisc { get; set; }
        public string userName { get; set; }
        public string timeStamp { get; set; }
    }
}
