//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonilaAccountingSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInfo
    {
        public int id { get; set; }
        public string storeName { get; set; }
        public string storeMob { get; set; }
        public string storePhone { get; set; }
        public string storeAddress { get; set; }
        public string storeSlogan { get; set; }
        public byte[] logo { get; set; }
    }
}
