//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RonilaAccountingSoftware.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInput
    {
        public int id { get; set; }
        public Nullable<int> storeInputDocNumber { get; set; }
        public string storeInputFactorNumber { get; set; }
        public Nullable<int> storeInputSupplierCode { get; set; }
        public string storeInputBuyDate { get; set; }
        public string storeInputDisc { get; set; }
        public string storeInputGoodsCode { get; set; }
        public Nullable<double> storeInputCount { get; set; }
        public Nullable<double> storeInputBuyPrice { get; set; }
        public Nullable<double> storeInputSellPrice { get; set; }
        public string storeInputShamsiProductionDate { get; set; }
        public string storeInputMiladiProductionDate { get; set; }
        public string storeInputShamsiExpireDate { get; set; }
        public string storeInputMiladiExpireDate { get; set; }
        public Nullable<int> storeInputAlarmDay { get; set; }
        public string storeInputAlarmDate { get; set; }
        public string userName { get; set; }
        public string timeStamp { get; set; }
    }
}
